---
network_identity_manage_hosts: true
network_identity_manage_resolv_conf: false
network_identity_resolv_conf_path: /etc/resolv.conf
network_identity_primary_ipv4: ""
network_identity_nameservers: []
network_identity_search_domains: []
network_identity_set_hostname: false
network_identity_hostname: ""
network_identity_fqdn: ""
network_identity_manage_loopback_fqdn: true
network_identity_manage_hosts_via_template: true
network_identity_cleanup_stale_hostname_entries: true
network_identity_extra_hosts_entries: []
