---
ssh_port: 22
firewall_default_input_policy: "DROP"
firewall_default_forward_policy: "DROP"
firewall_default_output_policy: "ACCEPT"
firewall_allow_ssh_from_anywhere: true
firewall_allowed_ssh_cidrs: []
firewall_allow_icmp_v4: true
firewall_allow_icmp_v6: true
firewall_enable_extra_input_hardening: true
